### ISSUE TITLE
return info on main article PDF from the API

### ISSUE THREAD

**Issue by IanMulvany** [elifesciences/elife-api#13]
This might be in the API already, but does the API return the full article PDF for all elife article types, or only the figure? If the latter, can we create an endpoint that returns info for all of our "normal" PDFs?

**Comment by gnott** [comment]
Two ways,

```
GET /v2/articles/{doi}/pdf
```
In the data returned, the item with type = article will be the main article PDF

```
GET /v2/articles/{doi}/pdf/article
```
Using the above endpoint, specifying "article" at the end, the data returned will only include the main article PDF (if it exists).
