### ISSUE TITLE
Figure PDF endpoint

### ISSUE THREAD

**Issue by gnott** [elifesciences/elife-api#2]
Given I have an article DOI
When I GET on the figure PDF endpoint
Then the JSON response includes a URL for the figure PDF

**File naming format**

elife*article number**-figures*
e.g. elife03005-figures.pdf

**Q.** Should we make the bucket receiving the figure PDF uploads world readable and web hosted? Or, should we copy the files to a different bucket?
**A.** Make world readable

**Q.** Should they be configured to be available from the CloudFront CDN?

**Comment by Melissa37** [comment]
TNQ delivery:
elife_2014_01977.figures.zip

To elife-articles
 
The only important part of the workflow is it not include the characters "pdf" in the zip file name, and not reuse any of the existing keywords: img, pdf, svg, jpg, video, xml

Graham:

I did a quick first draft of the figures PDF unzipping workflow. I won't launch it just now so I can ask a few questions

Q. Until we're able to update the new API (I think Luke is soon away) should I set it up to temporarily unzip to the old location and the new location?

Note: I set it up to unzip the file into the CDN bucket where all the other lens-like material goes, and I would then change the API to reflect this.

This is the path of my test on the dev workflow: http://cdn-dev.elifesciences.org/elife-articles/00778/figures-pdf/elife00778-figures.pdf

It means we can delete the elife-figures-pdf bucket when we're done.

Q. Is TNQ going to zip up all the existing figure PDF files and deliver, or do I need create a workflow to zip what they already sent individually?

The above question should answer my third question, whether we need to copy the PDF files from the old bucket to the new bucket. But, as long as someone supplies zipped PDF files for each then I can just run the workflow and voila!

**Comment by Melissa37** [comment]
Q. Until we're able to update the new API (I think Luke is soon away) should I set it up to temporarily unzip to the old location and the new location?
Yes please

Q. Is TNQ going to zip up all the existing figure PDF files and deliver, or do I need create a workflow to zip what they already sent individually?

No

The above question should answer my third question, whether we need to copy the PDF files from the old bucket to the new bucket. 
Yes please!

**Comment by gnott** [comment]
Thanks Melissa, a quick summary as of today,

- Workflow is deployed to unzip figure PDF zip files to both the old and new bucket locations
- I have a script to zip the PDFs from the old location, copy them to elife-articles bucket (as an archive). These will unzip to both locations too once they are uploaded

To do:
- Change the URL in the API to reflect the new location of the figure PDFs (once I've run the script and we're live on all fronts)

**Comment by Melissa37** [comment]
I had a call with Ganesan just now and wanted to confirm things from TNQ's end:

The archive has been delivered to elife-figure-pdfs as single PDF with naming convention, eg: elife00003-figures

For content from 1st Jan to today (28th Jan) files will be loaded to elife-figure-pdfs in a zipped folder each using the new file name: elife_2014_01977.figures.zip
For the PDF: elife_2014_01977.figures.pdf

From tomorrow (29th Jan), live content, will put in the figure-pdf bucket at same time as loading to HW.

Ganesan will let me know when he implements automation and delivery of the zipped files with the PMC content to elife-articles. 
It will be linked in with upgrade to JATS/3B2/Proof Central.

Hope that's all right and clear and works for everyone?!

**Comment by IanMulvany** [comment]
this has now been implemented.
